mywebsite_society_manager/urls.py
# -*- coding: utf-8 -*-
"""
--------------------------------------------------------------
  Copyright (C) 2018 - 2019 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.

  Credit for contents of this file goes to the project https://github.com/sabueso/ticketator!
--------------------------------------------------------------
"""

from django.contrib.auth import views as auth_views
from django.urls import path, re_path
from mywebsite_members import views as members_views

from .views import get_labels_list_flat_jx
from .views import group as vgroup
from .views import index
from .views import masterdata as vmasterdata
from .views import members as vmembers
from .views import priority as vpriorities
from .views import prospects as vprospects
from .views import queues as vqueues
from .views import right as vright
from .views import save_appsettings
from .views import search as vsearch
from .views import settings
from .views import states as vstates
from .views import tickets as vtickets
from .views import users as vusers
from .views import view_appsettings

app_name = 'society_manager'


urlpatterns = [
    # Dashboard, main screen spotted
    path('', index, name='index'),
    path('labels/get-list-flat', get_labels_list_flat_jx, name='get-labels-list-flat'),

    # Auth
    path('login/', members_views.LoginView.as_view(template_name='society_manager/auth/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='society_manager/auth/logout.html'), name='logout'),

    # Users
    path('settings/user/', vusers.list_users, name='user-list'),
    path('settings/user/create/', vusers.manage_user, name='user-create'),
    path('settings/user/<user_id>', vusers.manage_user, name='user-edit'),
    path('settings/user/delete/<user_id>', vusers.delete_user, name='user-delete'),
    path('settings/user/set_togglenavbar/', vusers.set_collapsednavbar_jx, name='user-set-collapsednavbar'),

    # Groups
    path('settings/groups/', vgroup.list_groups, name='group-list'),
    path('settings/groups/create/', vgroup.manage_group, name='group-create'),
    path('settings/groups/<group_id>', vgroup.manage_group, name='group-edit'),
    path('settings/groups/delete/<group_id>', vgroup.delete_group, name='group-delete'),

    # Rights
    path('settings/rights/', vright.list_rights, name='right-list'),
    path('settings/rights/create/', vright.manage_right, name='right-create'),
    path('settings/rights/<right_id>', vright.manage_right, name='right-edit'),
    path('settings/rights/archive/<right_id>', vright.archive_right, name='right-archive'),

    # States
    path('settings/state/', vstates.list_state, name='state-list'),
    path('settings/state/create/', vstates.manage_state, name='state-create'),
    path('settings/state/<state_id>', vstates.manage_state, name='state-edit'),
    path('settings/state/archive/<state_id>', vstates.archive_state, name='state-archive'),

    # Priorities
    path('settings/priorities/', vpriorities.list_priorities, name='priority-list'),
    path('settings/priorities/create/', vpriorities.manage_priority, name='priority-create'),
    path('settings/priorities/<priority_id>', vpriorities.manage_priority, name='priority-edit'),
    path('settings/priorities/archive/<priority_id>', vpriorities.archive_priority, name='priority-archive'),

    # Queues
    path('settings/queue/', vqueues.list_queues, name='queue-list'),
    path('settings/queue/create/', vqueues.manage_queue, name='queue-create'),
    path('settings/queue/<queue_id>', vqueues.manage_queue, name='queue-edit'),
    path('settings/queue/archive/<queue_id>', vqueues.archive_queue, name='queue-archive'),

    # Tickets
    path('tickets/', vtickets.list_tickets, name='tickets-list'),
    path('tickets/data/', vtickets.TicketListJson.as_view(), name='tickets-list-json'),
    path('tickets/<ticket_id>', vtickets.list_tickets, name='tickets-list'),
    path('tickets/state/<state_id>', vtickets.list_tickets_state,  name='tickets-list-state'),
    path('tickets/queue/<queue_id>', vtickets.list_tickets_queue, name='tickets-list-queue'),
    path('tickets/labels/<label>', vtickets.list_tickets_label, name='tickets-list-label'),
    path('tickets/create/', vtickets.manage_ticket, name='tickets-create'),
    path('tickets/create/auto/', vtickets.create_ticket_jx, name='tickets-auto-create'),
    path('tickets/edit/<ticket_id>', vtickets.manage_ticket, name='tickets-edit'),
    path('tickets/view/<ticket_id>', vtickets.view_ticket, name='tickets-view'),
    path('tickets/archive/<ticket_id>', vtickets.archive_ticket_jx, name='tickets-archive'),
    path('tickets/render_mail/<ticket_id>', vtickets.render_mail_jx, name='tickets-render-mail'),
    path('tickets/send_mail/<ticket_id>', vtickets.send_mail_jx, name='tickets-send-mail'),
    path('tickets/ignore_mail/<ticket_id>', vtickets.ignore_mail_jx, name='tickets-ignore-mail'),

    # Prospects
    path('prospects/', vprospects.list_prospects, name='prospects-list'),
    path('prospects/data/', vprospects.ProspectiveCompanyListJson.as_view(), name='prospects-list-json'),
    path('prospects/edit/<prospect_id>', vprospects.manage_prospect, name='prospects-edit'),
    path('prospects/view/<prospect_id>', vprospects.view_prospect, name='prospects-view'),
    path('prospects/archive/<prospect_id>', vprospects.archive_prospect, name='prospects-archive'),
    path('prospects/export/<prospect_id>', vprospects.export_prospect, name='prospects-export'),

    # Members
    path('members/', vmembers.list_members, name='members-list'),
    path('members/data/', vmembers.SocietyMemberListJson.as_view(), name='members-list-json'),
    path('members/create/<prospect_id>', vmembers.manage_member, name='members-create'),
    path('members/edit/<member_id>', vmembers.manage_member, name='members-edit'),
    path('members/view/<member_id>', vmembers.view_member, name='members-view'),
    path('members/archive/<member_id>', vmembers.archive_member, name='members-archive'),
    path('members/export/<member_id>', vmembers.export_member, name='members-export'),
    path('members/services/manage/', vmembers.manage_services_jx, name='used-services-create-edit'),
    path('members/services/archive/', vmembers.archive_services_jx, name='used-services-archive'),

    # Comments post
    path('tickets/add_comment/<ticket_id>', vtickets.add_comment_jx, name='tickets-add-comment'),
    path('tickets/get_comments/<ticket_id>', vtickets.get_comments_jx, name='tickets-get-comments'),
    path('tickets/archive_comment/', vtickets.archive_comment_jx, name='tickets-archive-comment'),

    # Percentage post
    path('tickets/set_percentage/<ticket_id>/range/', vtickets.set_percentage_jx, name='tickets-set-percentage'),
    path('tickets/get_percentage/<ticket_id>', vtickets.get_percentage_jx, name='tickets-get-percentage'),

    # Prospective company post
    path('tickets/add_company/', vtickets.add_company_jx, name='tickets-add-company'),

    # Microtask post
    path('tickets/add_microtask/<ticket_id>', vtickets.add_microtask_jx, name='tickets-add-microtask'),
    path('tickets/get_microtask/<mk_id>', vtickets.get_microtask_jx, name='tickets-get-microtask'),
    path('tickets/get_microtasks/<ticket_id>', vtickets.get_microtasks_jx, name='tickets-get-microtasks'),
    path('tickets/archive_microtask/', vtickets.archive_microtask_jx, name='tickets-archive-microtasks'),

    # Master data for countries
    path('settings/countries/', vmasterdata.list_countries, name='countries-list'),
    path('settings/countries/create/', vmasterdata.manage_countries, name='countries-create'),
    path('settings/countries/<country_id>', vmasterdata.manage_countries, name='countries-edit'),
    path('settings/countries/archive/<country_id>', vmasterdata.archive_countries, name='countries-archive'),

    # Master data for services
    path('settings/services/', vmasterdata.list_services, name='services-list'),
    path('settings/services/create/', vmasterdata.manage_services, name='services-create'),
    path('settings/services/<service_id>', vmasterdata.manage_services, name='services-edit'),
    path('settings/services/archive/<service_id>', vmasterdata.archive_services, name='services-archive'),

    # Master data for basic subscriptions
    path('settings/basic_subscriptions/', vmasterdata.list_basic_subscriptions, name='basic-subscriptions-list'),
    path('settings/basic_subscriptions/create/', vmasterdata.manage_basic_subscriptions, name='basic-subscriptions-create'),
    path('settings/basic_subscriptions/<basic_subscription_id>', vmasterdata.manage_basic_subscriptions, name='basic-subscriptions-edit'),
    path('settings/basic_subscriptions/archive/<basic_subscription_id>', vmasterdata.archive_basic_subscriptions, name='basic-subscriptions-archive'),

    # Master data for enrollment fees
    path('settings/enrollment_fees/', vmasterdata.list_enrollment_fees, name='enrollment-fees-list'),
    path('settings/enrollment_fees/create/', vmasterdata.manage_enrollment_fees, name='enrollment-fees-create'),
    path('settings/enrollment_fees/<enrollment_fee_id>', vmasterdata.manage_enrollment_fees, name='enrollment-fees-edit'),
    path('settings/enrollment_fees/archive/<enrollment_fee_id>', vmasterdata.archive_enrollment_fees, name='enrollment-fees-archive'),

    # Master data for payment types
    path('settings/payment_types/', vmasterdata.list_payment_types, name='payment-types-list'),
    path('settings/payment_types/create/', vmasterdata.manage_payment_types, name='payment-types-create'),
    path('settings/payment_types/<payment_type_id>', vmasterdata.manage_payment_types, name='payment-types-edit'),
    path('settings/payment_types/archive/<payment_type_id>', vmasterdata.archive_payment_types, name='payment-types-archive'),

    # Master data for payment intervals

test_website/urls.py
# -*- coding: utf-8 -*-
"""
--------------------------------------------------------------
  Copyright (C) 2018 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.
--------------------------------------------------------------

Website URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

import os

from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.db.utils import OperationalError
from django.urls import include, path, re_path
from django.views.generic import RedirectView
from django.views.i18n import JavaScriptCatalog

import menu
import notifications.urls
from filebrowser.sites import site
from mywebsite_home import views as homeviews

urlpatterns = [
    re_path(r'^favicon\.ico$', RedirectView.as_view(url='/static/mywebsite/img/default/favicon.gif')),
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('qr/', include("django_otp.urls")),  # enable QRcode for 2FA
    path('hitcount/', include('hitcount.urls', namespace='hitcount')),  # for hitcounts built-in AJAX post view
    path('captcha/', include('captcha.urls')),  # for captcha URLS
]

# handle language prefix in URL patterns
try:
    urlpatterns += i18n_patterns(
        path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
        path('tinymce/', include('tinymce.urls')),
        path('admin/filebrowser/', site.urls),
        # added custom view, see http://www.beardygeek.com/2010/03/adding-views-to-the-django-admin/
        path('admin/manual/', homeviews.manual, name="admin-manual"),
        path('admin/doc/', include('django.contrib.admindocs.urls')),
        path('admin/', admin.site.urls),
        # added javascript translation support, see
        # https://docs.djangoproject.com/en/dev/topics/i18n/translation/#internationalization-in-javascript-code
        path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
        # added website modules
        path('', include('mywebsite_home.urls', namespace='home')),
        path('society_manager/', include('mywebsite_society_manager.urls', namespace='society_manager')),
        path('blog/', include('mywebsite_blog.urls', namespace='blog')),
        path('members/', include('mywebsite_members.urls', namespace='members')),
        prefix_default_language=False
    )
except OperationalError:
    # happens when db doesn't exist yet, views.py should be importable without this side effect
    pass

# serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=os.path.join(settings.BASE_DIR, 'static'))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


@classmethod
def load_menus(c):
    """
    load_menus loads the menu.py file from test_website.
    """

    # we don't need to do this more than once
    if c.loaded:
        return

    try:
        __import__('test_website.menus', fromlist=["menu", ])
    except ImportError:
        pass

    c.loaded = True


# override menu.Menu.load_menus with our own method, to load custom_website.menus instead
menu.Menu.load_menus = load_menus

mywebsite_society_manager/views/group.py
# -*- coding: utf-8 -*-
"""
--------------------------------------------------------------
  Copyright (C) 2018 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.

  Credit for contents of this file goes to the project https://github.com/sabueso/ticketator!
--------------------------------------------------------------
"""

from django.contrib import messages
from django.contrib.auth.models import Group
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import gettext as _

from mywebsite_society_manager.forms import GroupForm


# List groups
def list_groups(request):
    if request.user.is_superuser:
        group_list = Group.objects.all().order_by("name")
        return render(request, 'society_manager/groups/list_groups.html', locals())
    else:
        messages.error(request, _('You don\'t have enough permissions to view this setting'))
        return redirect('society_manager:tickets-settings')


def manage_group(request, group_id=None):
    if request.user.is_superuser:
        if group_id:
            actual_group = get_object_or_404(Group, pk=group_id)
        else:
            actual_group = Group()

        # POST mode
        if request.method == 'POST':
            form = GroupForm(request.POST, instance=actual_group)
            if form.is_valid():
                form.save()
                return redirect('society_manager:group-list')
        else:
            # Non-POST mode, show only
            form = GroupForm(instance=actual_group)

        return render(request, 'society_manager/groups/create_edit_group.html', locals())

    else:
        messages.error(request, _('You don\'t have enough permissions to edit this setting'))
        return redirect('society_manager:group-list')


# Delete group
def delete_group(request, group_id=None):
    if request.user.is_superuser:
        if group_id:
            actual_group = get_object_or_404(Group, pk=group_id)
            actual_group.delete()
            return redirect('society_manager:group-list')
    else:
        messages.error(request, _('You don\'t have enough permissions to delete this setting'))
        return redirect('society_manager:group-list')

mywebsite_society_manager/templates/society_manager/dashboard/skel/bars.html
{% comment %}
  Copyright (C) 2018 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.

  Credit for contents of this file goes to the project https://github.com/sabueso/ticketator!
{% endcomment %}

{% include "society_manager/dashboard/skel/left_bar.html" %}
{% include "society_manager/dashboard/skel/upper_bar.html" %}

mywebsite_society_manager/templates/society_manager/dashboard/skel/left_bar.html
{% comment %}
  Copyright (C) 2018 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.

  Credit for contents of this file goes to the project https://github.com/sabueso/ticketator!
{% endcomment %}

{% load i18n static core_settings_data blog_tags %}
{% app_settings as appsettings %}

<div class="col-md-3 left_col">
    <div class="scroll-view">
        <div
            class="navbar nav_title"
            style="border: 0;"
        >
            <div class="profile">
                <a href="{% url 'society_manager:index' %}"><img
                        src="{{ logo }}"
                        style="margin-left: 15px; margin-top: 0px; width: 110px; height: 55px;"
                    ></a>
            </div>
        </div>

        <div class="clearfix"></div>
        <div class="clearfix"></div>

        <!-- sidebar menu -->
        <div
            id="sidebar-menu"
            class="main_menu_side hidden-print main_menu"
        >
            <div class="menu_section">
                <ul class="nav side-menu text-left">
                    <li class="nav-item">
                        <a href="{% url 'society_manager:index' %}"><i class="fa fa-home"></i> {% trans "Dashoard" %}
                            <span class="fa"></span></a>
                    </li>
                    {% all_queues_for_user perm_level='can_create' as queues %}
                    {% if queues %}
                    <li class="nav-item">
                        <a href="{% url 'society_manager:tickets-create' %}"><i class="fa fa-plus"></i>
                            {% trans "Add ticket" %}</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a href="{% url 'society_manager:tickets-list' %}"><i class="fa fa-reorder"></i>
                            {% trans "Tickets" %} <span class="fa"></span></a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'society_manager:prospects-list' %}"><i class="fa fa-vcard-o"></i>
                            {% trans "Prospects" %} <span class="fa"></span></a>
                    </li>
                    {% if appsettings.show_members %}
                    <li class="nav-item">
                        <a href="{% url 'society_manager:members-list' %}"><i class="fa fa-users"></i>
                            {% trans "Members" %} <span class="fa"></span></a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a><i class="fa fa-flag-o fa-fw"></i> {% trans "States" %} <span class="fa arrow"></span></a>
                        <ul class="nav child_menu">
                            {% all_states as states %}
                            {% for state in states %}
                            <li>
                                <a href="{% url 'society_manager:tickets-list-state' state.id %}">{{ state }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a><i class="fa fa-th-list"></i> {% trans "Queues" %}<span class="fa arrow"></span></a>
                        <ul class="nav child_menu">
                            {% all_queues_for_user perm_level='can_view' as queues %}
                            {% for queue in queues %}
                            <li>
                                <a href="{% url 'society_manager:tickets-list-queue' queue.id %}">{{ queue.name }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a><i class="fa fa-flag-o fa-fw"></i> {% trans "labels_field" %}<span class="fa arrow"></span></a>
                        <ul class="nav child_menu">
                            {% all_labels as labels %}
                            {% for label in labels %}
                            <li>
                                <a href="{% url 'society_manager:tickets-list-label' label|escape_raw %}">{{ label }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'society_manager:search' %}"><i class="fa fa-search"></i> {% trans "Search" %}
                        </a>
                    </li>
                    {% comment %} <li>
                        <a href="{% url 'society_manager:calendar' %}"><i class="fa fa-calendar"></i> Calendar</a>
                    </li> {% endcomment %}
                    <li class="nav-item">
                        <a href="{% url 'society_manager:tickets-settings' %}"><i class="fa fa-gear fa-fw"></i>
                            {% trans "Settings" %}</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

mywebsite_society_manager/templates/society_manager/dashboard/skel/upper_bar.html
{% comment %}
  Copyright (C) 2018 dsoft-app-dev.de and friends.

  This Program may be used by anyone in accordance with the terms of the
  German Free Software License

  The License may be obtained under http://www.d-fsl.org.

  Credit for contents of this file goes to the project https://github.com/sabueso/ticketator!
{% endcomment %}

{% load i18n static notifications_tags %}

<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav pull-right">
                <li class="nav-item">
                    <a
                        href="javascript:;"
                        class="dropdown-item"
                        data-toggle="dropdown"
                        aria-expanded="false"
                        style="padding-top: 17px; height: 100%"
                    >
                        <i class=" fa fa-bell" style="color: #73879c; margin-right: 10px"></i>
                        {% live_notify_badge %}
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class='dropdown-menu live_notify_list'></ul>
                </li>
                <li class="nav-item">
                    <a
                        href="javascript:;"
                        class="user-profile dropdown-item"
                        data-toggle="dropdown"
                        aria-expanded="false"
                    >
                        {% if request.user.avatar%}
                        <img
                            src="{{ request.user.avatar.url }}"
                            alt="..."
                        >
                        {% else %}
                        <img
                            src="{% static 'society_manager/img/user.png' %}"
                            alt=""
                        >
                        {% endif %}
                        {{ request.user }}
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu float-right">
                        {% comment %} <li><a href="{% url 'user-edit' request.user.id %}"> Profile</a></li>
                        <li>
                            <a href="{% url 'society_manager:tickets-settings' %}">
                                <span>Settings</span>
                            </a>
                        </li> {% endcomment %}
                        <!--<li><a href="javascript:;">Help</a></li>-->
                        <li class="nav-item"><a href="{% url 'society_manager:logout' %}"><i class="fa fa-sign-out float-right"></i>
                                {% trans "Log Out" %}</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</div>